### PR TITLE
[3.0.0] Full Rewrite

### LINKED ISSUE #13: [Bug] Invalid Player Causes Error
Playername>§g /fly off
[21:07:15] [Server thread/CRITICAL]: Error: "Call to a member function getName() on null" (EXCEPTION) in "plugins/FlyPE_dev-57.phar/src/AGTHARN/FlyPE/Main" at line 239
[21:07:15] [Server thread/CRITICAL]: #0 src/pocketmine/command/PluginCommand(54): AGTHARN\FlyPE\Main->onCommand(object pocketmine\Player, object pocketmine\command\PluginCommand, string[3] fly, array[1])
[21:07:15] [Server thread/CRITICAL]: #1 src/pocketmine/command/SimpleCommandMap(248): pocketmine\command\PluginCommand->execute(object pocketmine\Player, string[3] fly, array[1])
[21:07:15] [Server thread/CRITICAL]: #2 src/pocketmine/Server(1811): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\Player, string[7] fly off)
[21:07:15] [Server thread/CRITICAL]: #3 src/pocketmine/Player(2311): pocketmine\Server->dispatchCommand(object pocketmine\Player, string[7] fly off)
[21:07:15] [Server thread/CRITICAL]: #4 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(244): pocketmine\Player->chat(string[8] /fly off)
[21:07:15] [Server thread/CRITICAL]: #5 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
[21:07:15] [Server thread/CRITICAL]: #6 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
[21:07:15] [Server thread/CRITICAL]: #7 src/pocketmine/network/mcpe/protocol/BatchPacket(127): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
[21:07:15] [Server thread/CRITICAL]: #8 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
[21:07:15] [Server thread/CRITICAL]: #9 src/pocketmine/Player(3250): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
[21:07:15] [Server thread/CRITICAL]: #10 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
[21:07:15] [Server thread/CRITICAL]: #11 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[17] 81.0.36.151 29138, object raklib\protocol\EncapsulatedPacket, integer 0)
[21:07:15] [Server thread/CRITICAL]: #12 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
[21:07:15] [Server thread/CRITICAL]: #13 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
[21:07:15] [Server thread/CRITICAL]: #14 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
[21:07:15] [Server thread/CRITICAL]: #15 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
[21:07:15] [Server thread/CRITICAL]: #16 src/pocketmine/Server(2157): pocketmine\snooze\SleeperHandler->sleepUntil(double 1598296035.3948)
[21:07:15] [Server thread/CRITICAL]: #17 src/pocketmine/Server(1994): pocketmine\Server->tickProcessor()
[21:07:15] [Server thread/CRITICAL]: #18 src/pocketmine/Server(1588): pocketmine\Server->start()
[21:07:15] [Server thread/CRITICAL]: #19 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/container/, string[24] /home/container/plugins/)
[21:07:15] [Server thread/CRITICAL]: #20 src/pocketmine/PocketMine(304): pocketmine\server()
[21:07:15] [Server thread/CRITICAL]: #21 (11): require(string[71] phar:///home/container/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

### PR DESCRIPTION
**Pull request by AGTHARN**
This rewrite fixes the ugly and messy code with unused parts. The 3.0.0 branch is free for testing but is not to be used in servers until it is released as it may have bugs and is currently worked on for suggestions. So if you have any suggestions, do let me know in the Issues category.

- Improved Code Formatting
- Better Optimization
- Implement Ability to Change UI Texts (#10)
- Implement Particles (#8)
- Implement Configurable Flight Speed
- Implement Configurable Flight Effects
- Resolves Invalid Player Error (#13)
- Added More Tags to Messages

**TO DO:**
- [x] Fix Invalid Player Error (#13)
- [x] Ability to Change UI Texts (#10)
- [x] Fix a Same Mistake (#9)
- [x] Separate Main into Different Files
- [x] Implement Particles (#8)
- [x] Add Tags to All Message Configurations
- [x] Configurable Flight Speed
- [x] Configurable Flight Effects
- [x] Add All Particles
- [ ] Fix GitHub Desktop's Formatting Issues

### CODE REVIEW

**Comment by AGTHARN** [comment]
Feel free to test the 3.0.0 Rewrite. Greatly appreciated if any bugs are reported. [Download](https://poggit.pmmp.io/ci/AGTHARN/FlyPE/FlyPE/pr:55)

File: src/AGTHARN/FlyPE/Main.php [hunk 1]
```diff
@@ -27,319 +27,177 @@
...
+			$this->getScheduler()->scheduleRepeatingTask(new ParticleTask($this), $this->getConfig()->get("fly-particle-rate"));
+		}
 
-        $this->saveResource('config.yml');
-        $this->config = new Config($this->getDataFolder() . 'config.yml', Config::YAML);
-	    
-        $configversion = $this->config->get("config-version");
-	    
-	    if($configversion < "2"){
+		if ($this->getConfig()->get("config-version") < "3") {
```
Comment (HyperFlareMC) [inline src/AGTHARN/FlyPE/Main.php:65]: The current config version should be placed in a `CONFIG_VERSION` constant. It will make it easier if you need to have multiple usages, and will be easier to keep track of.

File: src/AGTHARN/FlyPE/Main.php [hunk 2]
```diff
@@ -27,319 +27,177 @@
...
-			    if($player->getAllowFlight() === true){
-				    $player->setFlying(false);
-				    $player->setAllowFlight(false);
-					$player->sendMessage(C::RED . $this->getConfig()->get("onjoin-flight-disabled"));
-				    return;
-			    }
-	    }
-    }
-	
-	public function BlacklistedWorldCheck($entity){
```
Comment (HyperFlareMC) [inline src/AGTHARN/FlyPE/Main.php:85]: Thank you for removing all these poorly camelCased methods :D

File: src/AGTHARN/FlyPE/Main.php [hunk 3]
```diff
@@ -27,319 +27,177 @@
...
-			if($player->getAllowFlight() === true){
-				$event->setCancelled();
-			}
+	/**
+	 * toggleFlight
+	 *
+	 * @param  Player $player
+	 * @return void
+	 */
+	public function toggleFlight(Player $player): void {
```
Comment (HyperFlareMC) [inline src/AGTHARN/FlyPE/Main.php:172]: Perhaps you could add another parameter here that takes a string with either `enable` or `disable`, so you could be in more control, and not relying on if they are already flying or not. Just make sure you change the code in this method a little bit to match it.

File: src/AGTHARN/FlyPE/commands/FlyCommand.php [hunk 4]
```diff
@@ -0,0 +1,112 @@
...
+namespace AGTHARN\FlyPE\commands;
+
+use pocketmine\command\CommandSender;
+use pocketmine\command\PluginCommand;
+use pocketmine\utils\TextFormat as C;
+use pocketmine\Player;
+
+use AGTHARN\FlyPE\Main;
+
+class FlyCommand extends PluginCommand {
```
Comment (HyperFlareMC) [inline src/AGTHARN/FlyPE/commands/FlyCommand.php:37]: Be careful using `PluginCommand` for future references. It is `final` in PM4, luckily this plugin only has one command, so it won't be difficult to transfer when PM4 is out. Just be careful in the future using it with PM3.

**Review by HyperFlareMC — COMMENTED** [review]
Fix all these little nit picks and all you'll have left are some small formatting things and you're good to go.

File: src/AGTHARN/FlyPE/commands/FlyCommand.php [hunk 5]
```diff
@@ -0,0 +1,112 @@
...
+		if (empty($args)) {
+			if ($this->plugin->doLevelChecks($sender) === true) {
+				$this->plugin->toggleFlight($sender);
+			}
+		}
+		if (isset($args[0])) {
+			$target = $this->plugin->getServer()->getPlayer($args[0]);
+
+			/** @phpstan-ignore-next-line */
+			if ($target->getName() === null || !$target instanceof Player) {
```
[the remark this answers is not in the document]
Comment (AGTHARN) [reply src/AGTHARN/FlyPE/commands/FlyCommand.php:89]: It's to fix #13. Is there a better way to do it? Should I just remove the getName() check?

File: src/AGTHARN/FlyPE/Main.php (hunk 2 above)
Comment (AGTHARN) [reply src/AGTHARN/FlyPE/Main.php:85]: No problem.

File: src/AGTHARN/FlyPE/commands/FlyCommand.php (hunk 4 above)
Comment (AGTHARN) [reply src/AGTHARN/FlyPE/commands/FlyCommand.php:37]: Okay. I will take note of it.

File: src/AGTHARN/FlyPE/Main.php (hunk 3 above)
Comment (AGTHARN) [reply src/AGTHARN/FlyPE/Main.php:172]: I feel that keeping it is better. I would have to add even more checks if I use `enable` or `disable` instead. However, I may consider doing that if I am adding an on/off button to the FlyUI instead of a toggle button.

File: src/AGTHARN/FlyPE/commands/FlyCommand.php [hunk 6]
```diff
@@ -0,0 +1,112 @@
...
+		if ($this->plugin->getConfig()->get("enable-fly-ui") === true) {
+			$this->plugin->openFlyUI($sender);
+			return false;
+		}
+		if (empty($args)) {
+			if ($this->plugin->doLevelChecks($sender) === true) {
+				$this->plugin->toggleFlight($sender);
+			}
+		}
+		if (isset($args[0])) {
```
[the remark this answers is not in the document]
Comment (AGTHARN) [reply src/AGTHARN/FlyPE/commands/FlyCommand.php]: There's a return statement after the checks.

File: src/AGTHARN/FlyPE/lists/ParticleList.php [hunk 7]
```diff
@@ -0,0 +1,201 @@
...
+use AGTHARN\FlyPE\Main;
+
+class ParticleList {
+
+    /**
+     * plugin
+     * 
+     * @var Main
+     */
+    private $plugin;
```
Comment (HyperFlareMC) [inline src/AGTHARN/FlyPE/lists/ParticleList.php:67]: Unused property.

Comment (HyperFlareMC) [inline src/AGTHARN/FlyPE/lists/ParticleList.php:67]: Unused property, you can also remove the `$plugin` parameter in the constructor for this class, just make sure you change it in the areas where you create new `ParticleList` objects.

File: src/AGTHARN/FlyPE/tasks/ParticleTask.php [hunk 8]
```diff
@@ -0,0 +1,68 @@
...
+ * GNU General Public License for more details.
+ *
+ * You should have received a copy of the GNU General Public License
+ * along with this program.  If not, see <http://www.gnu.org/licenses/>.
+ */
+
+namespace AGTHARN\FlyPE\tasks;
+
+use pocketmine\scheduler\Task;
+use pocketmine\utils\TextFormat as C;
```
Comment (HyperFlareMC) [inline src/AGTHARN/FlyPE/tasks/ParticleTask.php:31]: Unused import.

File: src/AGTHARN/FlyPE/tasks/EffectTask.php [hunk 9]
```diff
@@ -0,0 +1,74 @@
...
+ * GNU General Public License for more details.
+ *
+ * You should have received a copy of the GNU General Public License
+ * along with this program.  If not, see <http://www.gnu.org/licenses/>.
+ */
+
+namespace AGTHARN\FlyPE\tasks;
+
+use pocketmine\scheduler\Task;
+use pocketmine\utils\TextFormat as C;
```
Comment (HyperFlareMC) [inline src/AGTHARN/FlyPE/tasks/EffectTask.php:31]: Unused import.

File: src/AGTHARN/FlyPE/lists/ParticleList.php [hunk 10]
```diff
@@ -0,0 +1,201 @@
...
+ * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+ * GNU General Public License for more details.
+ *
+ * You should have received a copy of the GNU General Public License
+ * along with this program.  If not, see <http://www.gnu.org/licenses/>.
+ */
+
+namespace AGTHARN\FlyPE\lists;
+
+use pocketmine\utils\TextFormat as C;
```
Comment (HyperFlareMC) [inline src/AGTHARN/FlyPE/lists/ParticleList.php:30]: Unused import.

**Review by HyperFlareMC — COMMENTED** [review]
These are just little things - unused imports and such. As long as you've tested the flight speed and particles, it looks good.

**Comment by HyperFlareMC** [comment]
Looks good, as long as it's tested it should be good. Formatting will be fixed in a separate commit.
